typelift/Swiftz

swiftz.xcodeproj/project.pbxproj
swiftz/Maybe.swift
swiftzTests/DataTests.swift

Would accidentally force the None in comparisons with mixed Just and
None.

Fix Maybe Equality

---

swiftz.xcodeproj/project.pbxproj
swiftz/List.swift
swiftzTests/DataTests.swift

First off, SHAME!
Secondly, the eager implementation of this thing does not gel with the laziness of the data structure.  There's so much unnecessary evaluation of the list it makes it almost meaningless as a data structure compared to the built-in one.  We can "fix" that with recursion but then we'd lose both the magic of benign effects and any control over the performance of each of the combinators.
Rock and a hard place, eh?

Robust Lists

---

swiftz/Sections.swift
swiftz_core/swiftz_core/Sections.swift

Apparently Float80 exists in debug, but not release?

Fix iOS Carthage Build

---

Cartfile.resolved
Swiftz/Sections.swift

Completes sections maintenance on both libraries.

Fix Disequality Sections

---

Cartfile.resolved
README.md
Swiftz-iOS.xcodeproj/project.pbxproj
Swiftz.xcodeproj/project.pbxproj
Swiftz/JSON.swift
Swiftz/JSONKeypath.swift
Swiftz/Operators.swift
Swiftz/Semigroup.swift
SwiftzTests/JSONSpec.swift
SwiftzTests/PartyExample.swift
SwiftzTests/UserExample.swift

This pull request simplifies the JSON machinery and adds the ability to subscript deeper into nested structures using the new `JSONKeypath` Monoid.

We Can Go Deeper

---

Swiftz/ArrayExt.swift
Swiftz/JSON.swift
Swiftz/Set.swift
SwiftzTests/ArrayExtSpec.swift

Uses the Array Matcher stuff to simplify ArrayExt.

An Array of Simplifications

---

Swiftz.podspec

Add a podspec file

---

Swiftz.xcodeproj/project.pbxproj
Swiftz/Applicative.swift
Swiftz/Pointed.swift
Swiftz/ResultExt.swift
SwiftzTests/ResultSpec.swift

In retrospect, a much better name for this branch.

Test Result

---

Cartfile.resolved
Swiftz/Function.swift
Swiftz/JSON.swift
Swiftz/List.swift
Swiftz/NonEmptyList.swift
Swiftz/StringExt.swift
SwiftzTests/ResultSpec.swift

- A couple simplifications, but not much else.

Support Swift 2.0 beta 2

---

Swiftz.xcodeproj/project.pbxproj
Swiftz/ArrayExt.swift
Swiftz/Function.swift
Swiftz/Those.swift
SwiftzTests/ArrayExtSpec.swift
SwiftzTests/FunctionSpec.swift

- Tests some Arrow laws
- Adds several missing Array combinators

Arrow and Array Improvements

---

README.md

This one has been bugging me for the longest time.

Fix Build Status Link

---

Swiftz.xcodeproj/project.pbxproj
Swiftz/ArrayExt.swift
Swiftz/List.swift
Swiftz/NonEmptyList.swift
Swiftz/Semigroup.swift
SwiftzTests/ArrayExtSpec.swift
SwiftzTests/ListSpec.swift
SwiftzTests/NonEmptyListSpec.swift

And discover some nasty bugs along the way.

Update List With New Array Kit

---

Swiftz/ArrayExt.swift
Swiftz/EitherExt.swift
Swiftz/JSONKeypath.swift
Swiftz/Maybe.swift
Swiftz/Monoid.swift
Swiftz/OptionalExt.swift
Swiftz/Semigroup.swift
Swiftz/StringExt.swift
SwiftzTests/JSONSpec.swift
SwiftzTests/MonoidSpec.swift
SwiftzTests/StringExtSpec.swift

mzero -> mempty

---

Cartfile.resolved
Swiftz/NonEmptyList.swift
Swiftz/OptionalExt.swift
SwiftzTests/ListSpec.swift
SwiftzTests/UserExample.swift

<strike> Still kinks to work out, but here it is. </strike>
There is no sadness like the New Beta Workaround Sadness.

Update to beta 6

---

Swiftz.podspec

Updated the podspec to include `Operadics`.

Podspec update

---

Swiftz/OptionalExt.swift

Add SequenceType conformance to Optional

---

Swiftz/JSON.swift
SwiftzTests/JSONSpec.swift
SwiftzTests/ShapeExample.swift
SwiftzTests/UserExample.swift

Support for NSNumber, Int, Int64, UInt64, Bool, Double, and Float)
Related issue: #263

Improved JSON serialization for numbers (with unit tests)

---

Swiftz/ArrayExt.swift
Swiftz/DictionaryExt.swift
Swiftz/JSON.swift
SwiftzTests/ArrayExtSpec.swift
SwiftzTests/ArrowExtSpec.swift

Refactored Dictionary generic syntax to use literals: Dictionary<Key, Value> to [Key: Value]
Refactored Array generic syntax to use literals: Array<A> to [A]
#272

Literals refactor

---

Swiftz.xcodeproj/project.pbxproj
Swiftz/Reader.swift
SwiftzTests/ReaderSpec.swift

A reader monad with some simple test cases

Reader monad

---

.travis.yml
Cartfile.resolved
Swiftz.xcodeproj/project.pbxproj
Swiftz/Identity.swift
Swiftz/Reader.swift
Swiftz/Unit.swift
SwiftzTests/ArrayExtSpec.swift
SwiftzTests/ArrowExtSpec.swift
SwiftzTests/DictionaryExtSpec.swift
SwiftzTests/FunctionSpec.swift
SwiftzTests/IdentitySpec.swift
SwiftzTests/ListSpec.swift
SwiftzTests/MonoidSpec.swift
SwiftzTests/NonEmptyListSpec.swift
SwiftzTests/OptionalExtSpec.swift
SwiftzTests/ProxySpec.swift
SwiftzTests/ReaderSpec.swift
SwiftzTests/UnitSpec.swift

Adds more Applicative, Monad, and Comonad law tests

Test More Laws!

---

Swiftz.xcodeproj/project.pbxproj
Swiftz/Stream.swift
SwiftzTests/StreamSpec.swift

What's in this pull request?
============================
- Fixes `Stream.drop(_)` so it no longer over-drops elements.
- Adds a `Stream` spec to the test suite so this doesn't happen again.

Uninterrupted stream of consciousness

---

.travis.yml
Cartfile.private
Cartfile.resolved
Swiftz.xcodeproj/project.pbxproj

What's in this pull request?
============================
We'll branch from here for the Swift 2.3 release.

Bump dependencies for 2.3

---

README.md

What's in this pull request?
============================
Added steps to setup in Swift Package Manager.
Why merge this pull request?
============================
To make support for SPM easier to find.
What's worth discussing about this pull request?
================================================
Nothing I can think of.
What downsides are there to merging this pull request?
======================================================
Nothing I can think of.

Added steps to setup in SPM in ReadMe

---

.travis.yml
Cartfile.private
Cartfile.resolved
Package.swift

Removes explicit build products from the package manifest.

Call of the postal horn

---

Swiftz.podspec

[podspec] Fix source_files
